[book]
title = "Rinaldo's Stream of Consciousness"
authors = ["Rinaldo Rex"]
language = "en"

[output.html.fold]
enable = true    # include support for printable output
level = 1

[output.html]
no-section-label = true
mathjax-support = true

[preprocessor.footnote]
