[book]
title = "Rinaldo's Stream of Consciousness"
authors = ["Rinaldo Rex"]
language = "en"

[output.html.fold]
enable = true    # include support for printable output
level = 2

[output.html]
no-section-label = true
mathjax-support = true

[preprocessor.footnote]

[preprocessor.reading-time]
words-per-minute = 150

[preprocessor.gitinfo]
enable = true

# choose placement(s)
header = false   # default: false
footer = true    # default: true

# common formatting
font-size   = "0.9em"
separator   = " • "
date-format = "%Y-%m-%d"
time-format = "%H:%M:%S"
branch      = "main"
hyperlink   = true  # make hash/branch clickable when possible

# optional timezone handling
timezone = "local"   # "local" (default) | "utc" | "source" | "fixed:+02:00"

[preprocessor.gitinfo.message]
footer = "Last updated: <em>{{date}}</em>"
