[book]
authors = ["Rinaldo Rex"]
language = "en"
multilingual = false
src = "src"
title = "Rinaldo's stream of consciousness"
description = "A stream of consciousness of me evolving and exploring life as I live it"
google_analytics_id = "UA-167980195-1"

[output.html]
preferred-dark-theme = "Navy"

[output.html.fold]
enabled = true
level = 0

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3
copy-js = true